#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <stdbool.h>

// Function to generate Fibonacci series
void generateFibonacci(int n, int arr[]) {
    arr[0] = 0;
    if (n > 1) arr[1] = 1;

    for (int i = 2; i < n; i++) {
        arr[i] = arr[i - 1] + arr[i - 2];
    }
}

// Function to check if a number is prime
bool isPrime(int num) {
    if (num < 2) return false;
    for (int i = 2; i * i <= num; i++) {
        if (num % i == 0) {
            return false;
        }
    }
    return true;
}

int main() {
    int n;
    printf("Enter the length of Fibonacci series: ");
    scanf("%d", &n);

    if (n <= 0) {
        printf("Invalid series length. Exiting program.\n");
        return 1;
    }

    int fib[n]; // Array to store the Fibonacci series
    pid_t pid;

    pid = fork(); // Create child process

    if (pid < 0) {
        perror("Fork failed");
        exit(1);
    }

    if (pid == 0) { // Child process
        printf("Child Process: Generating Fibonacci series...\n");
        generateFibonacci(n, fib);

        printf("Child Process: Fibonacci series generated successfully.\n");
        exit(0);
    } else { // Parent process
        wait(NULL); // Wait for child to complete
        printf("Parent Process: Fibonacci series generated by child process:\n");

        // Display the Fibonacci series
        for (int i = 0; i < n; i++) {
            printf("%d ", fib[i]);
        }
        printf("\n");

        // Identify prime Fibonacci numbers
        printf("Parent Process: Prime Fibonacci numbers and their positions:\n");
        for (int i = 0; i < n; i++) {
            if (isPrime(fib[i])) {
                printf("Prime Number: %d at Position: %d\n", fib[i], i + 1);
            }
        }
    }

    return 0;
}